site_name: Fosshost Docs
theme:
  name: material
  logo: /assets/favicon.png
  favicon: /assets/favicon.png
  palette:
    primary: red

repo_name: fosshostorg/public-docs
repo_url: https://github.com/fosshostorg/fosshostorg/public-docs
edit_uri: https://github.com/fosshostorg/fosshostorg/public-docs/edit/main/docs/
markdown_extensions:
  - toc:
      permalink: true
  - md_in_html
copyright: Content is available under the Public Domain, by Fosshost.

